name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'RedstoneWizard08'
        repository: 'IcarusModMerger'
    - name: Access cloned repository content
      run: |
        cd IcarusModMerger
        ls -la
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - uses: actions/checkout@v5
    - name: Download release artifact
      uses: actions/download-artifact@v5
      with:
        name: IcarusModMerger
        path: ./IcarusModMerger
