name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'RedstoneWizard08'
        repository: 'IcarusModMerger'
    - name: Access cloned repository content
      run: |
        cd IcarusModMerger
        ls -la
        cargo build -r --verbose --bins
        cp ./target/release/icarus-mod-merger ~/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust-artifact
        path: ~/icarus-mod-merger
